# Unique name for this workflow
name: Validate PR on develop branch

# Definition of when the workflow should run
on:
  pull_request:
    types: [opened, synchronize]
    branches: [develop]
    paths:
      - "force-app/**"

jobs:
  perform-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Ensure Node.js v20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Ensure Java 11
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Ensure Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Install Salesforce CLI plugins
        run: |
          sf plugins install code-analyzer@latest
          sf plugins install sfdx-git-delta

      - name: Create delta packages
        run: |
          mkdir -p changed-sources
          # Generate delta between last commit and HEAD for force-app only
          sf sgd source delta --to "HEAD" --from "HEAD~1" --output "changed-sources" --generate-delta --source "force-app/"
          echo "[INFO] Diff generated"

      - name: Run Scanner
        run: |
          cd changed-sources
          sf code-analyzer run --rule-selector Recommended --workspace . --view table --config-file ../code-analyzer.yml
          cd ..

      - name: Deploy to environment with all local tests
        run: |
          echo "${{ secrets.JWT_SECRET_KEY }}" > server.key
          sf org login jwt \
            --username "${{ secrets.DEPLOYMENT_USERNAME }}" \
            --jwt-key-file server.key \
            --client-id "${{ secrets.CONSUMER_KEY }}" \
            --instance-url "${{ vars.INSTANCE_URL }}" \
            --set-default
          sf project deploy start --source-dir "changed-sources/force-app" --test-level RunLocalTests
